[[redirects]]
  from = "/https://gentle-anchorage-12056.herokuapp.com"
  to = "https://employeesdetails.netlify.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"